<a href="https://colab.research.google.com/github/ESOJ74/lil-azure-machine-learning-y-ai/blob/master/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

Grafo

In [ ]:
x = tf.constant([3, 5, 7])
y = tf.constant([1, 2, 3])
z = tf.add(x, y)
print (t)

Tensor("Add_2:0", shape=(3,), dtype=int32)


Ejecucion de session() de forma perezosa

In [ ]:
tf.compat.v1.disable_eager_execution()
# Construct a `Session` to execute the graph.
with tf.compat.v1.Session() as sess:
# Execute the graph and store the value that `e` represents in `result`.
  result = sess.run(z)
  print(result)

[ 4  7 10]


Ejecucion de session() de forma imperativa

In [ ]:
with tf.compat.v1.Session() as sess:
  x = tf.constant([3, 5, 7])
  y = tf.constant([1, 2, 3])            #el grafo debe ir en la sesion
  z = tf.add(x, y)
  print (sess.run(z))


[ 4  7 10]


Es posible evaluar una lista de tensors

In [ ]:
#grafo
x = tf.constant([3, 5, 7])
y = tf.constant([1, 2, 3])           
z1 = tf.add(x, y)             #tambien valdrá z1= x + y simplemente
z2 = x * y
z3 = z2 - z1

tf.compat.v1.disable_eager_execution()
with tf.compat.v1.Session() as sess:
    a1, a3 = sess.run([z1,z3])
    print (a1)
    print (a3)

[ 4  7 10]
[-1  3 11]


Escribir un grafo

In [ ]:
import tensorflow.compat.v1 as tf
#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior()
#grafo
x = tf.constant([3, 5, 7], name="x")
y = tf.constant([1, 2, 3], name="y")           
z1 = tf.add(x, y, name="z1")             #tambien valdrá z1= x + y simplemente
z2 = x * y
z3 = z2 - z1

tf.disable_eager_execution()
with tf.Session() as sess:
  with tf.summary.FileWriter('sumaries',sess.graph) as writer:
    a1,a3 = sess.run([z1,z3])

In [ ]:
!ls sumaries

events.out.tfevents.1595765144.64bb97340128
events.out.tfevents.1595765249.64bb97340128
events.out.tfevents.1595765285.64bb97340128
events.out.tfevents.1595765343.64bb97340128
events.out.tfevents.1595765348.64bb97340128
events.out.tfevents.1595765416.64bb97340128
events.out.tfevents.1595765419.64bb97340128


extraer tensores

In [ ]:
import tensorflow.compat.v1 as tf

x = tf.constant([[3, 5, 7],
                [4, 6, 8]])
y = x[:, 1]
tf.disable_eager_execution()
with tf.Session() as sess:
  print (y.eval())



[5 6]


In [ ]:
y=x[1,:]
with tf.Session() as sess:
  print (y.eval())

y=x[1,0:2]
with tf.Session() as sess:
  print (y.eval())

[4 6 8]
[4 6]


reshaped

In [ ]:
import tensorflow.compat.v1 as tf

x = tf.constant([[3, 5, 7],
                [4, 6, 8]])
y = tf.reshape(x,[3,2])
tf.disable_eager_execution()
with tf.Session() as sess:
   print ("solucion 1  {} ".format(y.eval()))

y = tf.reshape(x,[3,2])[1, :]
tf.disable_eager_execution()
with tf.Session() as sess:
  print ("solucion 2   " + str(y.eval()))

solucion 1  [[3 5]
 [7 4]
 [6 8]] 
solucion 2   [7 4]
