# Cadenas de Markov

Una cadena de Markov (CM) es un tipo particular de proceso estocástico.
Una CM tiene probabilidades de transición estacionarias, es decir, no dependen del tiempo.
Las probabilidades del estado siguiente dependen únicamente del estado presente y no de los estados pasados.

Esto permite que la CM se pueda representar de manera compacata con un grafo.
Por ejemplo:

![title](ejemplo2estados.png)

En este caso la CM tiene dos estados.
Los parámetros de las aristas son las probabilidades de transición de estado.

Por ejemplo, en esta CM la probabilidad de transitar del estado 1 al estado 2 es de 0.7.

Esto lo denotamos como $P(s^{t+1}{=}2 \mid s^{t}{=}1) = 0.7$.

## Matrices y Cadenas de Markov 

Las probabilidades de transición de una cadena de Markov se pueden representar de manera matricial.

En este caso la matrix de probabilidades de transición $T$ queda dada por:

$T = 
\begin{bmatrix}
0.3&0.6\\
0.7&0.4
\end{bmatrix}
$

En python podemos utilizar el paquete científico numpy. 
La manera de representar esta matriz en Python es como sigue:


In [20]:
import numpy as np

T = np.matrix([[0.3,0.6],[0.7,0.4]])

print(T)

[[0.3 0.6]
 [0.7 0.4]]


La evolución de la distribución de probabilidad $x$ para los dos estados esta dada por la ecuación:

$
x = T x
$

Por ejemplo si sabemos con certeza que estamos en el estado 1 y esto se representa como:

$
x = 
\begin{bmatrix}
1\\
0
\end{bmatrix}
$

Es decir la probabilidad de estar en el estado 1 es 1 y de estar en el estado 2 es 0.

Si queremos saber como será la distribución de probabilidad para los estados en el tiempo siguiente hacemos:

$x^{t+1} = 
\begin{bmatrix}
0.3&0.6\\
0.7&0.4
\end{bmatrix}
\begin{bmatrix}
1\\
0
\end{bmatrix}
=
\begin{bmatrix}
0.3\\
0.7
\end{bmatrix}
$

Es decir la probabilidad de estar en el estado 1 es 0.3 y de transitar al estado 2 es 0.7.


Si queremos saber que pasará dos tiempos en el futuro, iteramos la ecuación:

$x^{t+2} = 
\begin{bmatrix}
0.3&0.6\\
0.7&0.4
\end{bmatrix}
\begin{bmatrix}
0.3&0.6\\
0.7&0.4
\end{bmatrix}
\begin{bmatrix}
1\\
0
\end{bmatrix}
=
\begin{bmatrix}
0.3&0.6\\
0.7&0.4
\end{bmatrix}^2
\begin{bmatrix}
1\\
0
\end{bmatrix}
$

Con ayuda de numpy podemos calcular esta matriz:


In [21]:
x = np.matrix([[1],[0]])
print('x =\n'+str(x))
x_1 = np.matmul(T,x)
print('x(t+1)=\n'+str(x_1))
x_2 = np.matmul(T,x_1)
print('x(t+2)=\n'+str(x_2))

x =
[[1]
 [0]]
x(t+1)=
[[0.3]
 [0.7]]
x(t+2)=
[[0.51]
 [0.49]]


Para comprobar que esto es lo mismo que elevar la matriz  T  al cuadrado y multiplicar por  x  podemos recurrir a la función matrix_power de numpy.

In [22]:
x_2 = np.matmul(np.linalg.matrix_power(T,2),x)
print('x(t+2)=\n'+str(x_2))

x(t+2)=
[[0.51]
 [0.49]]


Bajo ciertas condiciones, existe una distribución de probabilidad estacionaria sobre los estados. Esto significa que no importa cual se la distribución de probabilidad inicial, al iterar la ecuación la distribución converge a una distribución que no cambia.

Por ejemplo definamos un método para encontrar la distribución de probabilidad al tiempo t dada una condición inicial  x :

In [23]:
def calcula_dist(T,x_0,n):
    x_n = np.matmul(np.linalg.matrix_power(T,n),x_0)
    print('x(t+'+str(n)+')=\n'+str(x_n))

Usemos esta función para encontrar la distribución al tiempo 5:

In [24]:
x_5 = calcula_dist(T,x,5)

x(t+5)=
[[0.46023]
 [0.53977]]


Veamos como cambia la distribución con las primeras 10 iteraciones:

In [25]:
for i in range(10):
    calcula_dist(T,x,i)

x(t+0)=
[[1.]
 [0.]]
x(t+1)=
[[0.3]
 [0.7]]
x(t+2)=
[[0.51]
 [0.49]]
x(t+3)=
[[0.447]
 [0.553]]
x(t+4)=
[[0.4659]
 [0.5341]]
x(t+5)=
[[0.46023]
 [0.53977]]
x(t+6)=
[[0.461931]
 [0.538069]]
x(t+7)=
[[0.4614207]
 [0.5385793]]
x(t+8)=
[[0.46157379]
 [0.53842621]]
x(t+9)=
[[0.46152786]
 [0.53847214]]


Observamos una rápida convergencia a los valores.

¿Qué tanto tenemos que iterar la ecuación para encontrar la distribución?

Esto puede resolverse más fácilmente si observamos que lo que queremos encontrar es $x^{\text{*}}$ tal que:

$x^{\text{*}} = T x^{\text{*}}$

Esto es equivalente a resolver el problema de encontrar los vectores característicos de la matriz $T$.

Los vectores característicos de una matriz son aquellos que no cambian de dirección cuando se aplica la transformación lineal $T$ (es decir cuando se multiplica por $T$).

En numpy podemos encontrar esto usando *linalg.eig*

In [26]:
l,v = np.linalg.eig(T)
print(l)
print(v)

[-0.3  1. ]
[[-0.70710678 -0.65079137]
 [ 0.70710678 -0.7592566 ]]


Nos interesa el eigenvector que corresponde con el eigenvalor 1. En este caso el vector que esta como segunda columna en v. Lo extraemos y normalizamos:

In [27]:
x_s = v[:,1] / sum(v[:,1])
print(x_s)

[[0.46153846]
 [0.53846154]]


Considera la CM representada por el siguiente diagrama:



![title](markovchain.png)

En tu tarea tendras que encontrar la distribución de probabilidad estacionaria.

Comienza identificando la matriz de probabilidades de transición $T$ correspondiente.

Comprueba que obtienes lo mismo elevando $T$ a una potencia grande y calculando los vectores característicos de T.

In [67]:
# comienza por definir la matriz de probabilidad T
T = np.matrix([[0.7,0.4,0.2],[0.1,0.4,0.2],[0.2,0.2,0.6]])

print(T)

# define un estado inicial, por ejemplo que el agente se encuentra en b
# x = 
x = np.matrix([[0],[1],[0]])
print('x =\n'+str(x))
x_1 = np.matmul(T,x)
print('x(t+1)=\n'+str(x_1))
x_2 = np.matmul(T,x_1)
print('x(t+2)=\n'+str(x_2))
# ¿que pasa al iterar 50 veces la ecuación?
#calcula_dist(T,x,50)
for i in range(49):
    calcula_dist(T,x,i)
# Calcula eigenvectores
l,v = np.linalg.eig(T)
print(l)
print(v)

# Identifica la columna correspondiente para el eigenvalor 1
# recuerda que en Python los índices comienzan en 0
columna  = 0

#normaliza para obtener la distribución
x_s = v[:,columna] / sum(v[:,columna])


#compara tus resultados ¿es la mísma distribución?

[[0.7 0.4 0.2]
 [0.1 0.4 0.2]
 [0.2 0.2 0.6]]
x =
[[0]
 [1]
 [0]]
x(t+1)=
[[0.4]
 [0.4]
 [0.2]]
x(t+2)=
[[0.48]
 [0.24]
 [0.28]]
x(t+0)=
[[0.]
 [1.]
 [0.]]
x(t+1)=
[[0.4]
 [0.4]
 [0.2]]
x(t+2)=
[[0.48]
 [0.24]
 [0.28]]
x(t+3)=
[[0.488]
 [0.2  ]
 [0.312]]
x(t+4)=
[[0.484 ]
 [0.1912]
 [0.3248]]
x(t+5)=
[[0.48024]
 [0.18984]
 [0.32992]]
x(t+6)=
[[0.478088]
 [0.189944]
 [0.331968]]
x(t+7)=
[[0.4770328]
 [0.19018  ]
 [0.3327872]]
x(t+8)=
[[0.4765524 ]
 [0.19033272]
 [0.33311488]]
x(t+9)=
[[0.47634274]
 [0.1904113 ]
 [0.33324595]]
x(t+10)=
[[0.47625363]
 [0.19044799]
 [0.33329838]]
x(t+11)=
[[0.47621641]
 [0.19046423]
 [0.33331935]]
x(t+12)=
[[0.47620105]
 [0.19047121]
 [0.33332774]]
x(t+13)=
[[0.47619477]
 [0.19047414]
 [0.3333311 ]]
x(t+14)=
[[0.47619221]
 [0.19047535]
 [0.33333244]]
x(t+15)=
[[0.47619118]
 [0.19047585]
 [0.33333298]]
x(t+16)=
[[0.47619076]
 [0.19047605]
 [0.33333319]]
x(t+17)=
[[0.47619059]
 [0.19047613]
 [0.33333328]]
x(t+18)=
[[0.47619052]
 [0.19047617]
 [0.33333331]]
x

In [68]:
#Descomenta y ejecuta la siguiente linea. Copia el resultado en un archivo para someter tu tarea.
print(x_s)

[[0.47619048]
 [0.19047619]
 [0.33333333]]
